openapi: 3.0.1
info:
  title: delivery
  description: API Definition of delivery
  version: 1.0.0
servers:
- url: http://localhost:8290/delivery
paths:
  /getDelivery:
    get:
      responses:
        default:
          description: Default response
  /newDelivery:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /{delivery_id}:
    delete:
      parameters:
      - name: delivery_id
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
    patch:
      parameters:
      - name: delivery_id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
