openapi: 3.0.1
info:
  title: payment
  description: API Definition of payment
  version: 1.0.0
servers:
- url: http://localhost:8290/payment
paths:
  /getPayment:
    get:
      responses:
        default:
          description: Default response
